### ISSUE TITLE
How to configure multiple objects in to a single array

### ISSUE THREAD

**Issue by Soumyakulkarni5** [Sudhirmiglani/node-json-transformer#1]
Is there a way to configure multiple objects in to a single array.
Ex: below in the input mapping that need to be transformed in to single array
Input:
{
x:"a",
y:"b",
z : "c"
}

Expected out put:
{ 
 result : [ { name: "first item", value : "x"}, {name:"second item", value:"y"} ...}]
}

Thank you

**Comment by Sudhirmiglani** [comment]
This feature is not yet supported, will add this feature in couple of days if this is required

**Comment by Soumyakulkarni5** [comment]
Thank you Sudhir. First item is not dynamic. I will try this out.

**Comment by Sudhirmiglani** [comment]
Cheers !!
